-keep class com.argonaut.MainApplication
-keep class com.argonaut.MainApplication { *; }
-keep class com.argonaut.showjava.utils.logging.** { *; }
-keep class com.argonaut.showjava.test.** { *; }
-keep class androidx.test.** { *; }
-keep class androidx.multidex.** { *; }
-keep class kotlin.** { *; }
